# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Argentina DevDay"
email: "argentinadevday@gmail.com"
description: "Evento para unirse al desarrollo de la comunidad Argentina."
baseurl: "/argentinadevday.github.io"
# url: "gdgrio.org/riodevday"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Los seres humanos que disfrutan de la tecnología"
organizerAlternateName: "Los seres humanos que disfrutan de la tecnología"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "argentinadevday@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://argentinadevday.github.io/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, rio"
twitterAccount: "@gdgrio"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/yD2sEXxqfsssUZLn2"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programación"}
 - {permalink: "/speakers/", text: "Charlantes"}
 - {permalink: "/team/", text: "Los organizadores"}
 - {permalink: "/communities/", text: "Proyectos"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
# bottomNavigationLinks:
#  - {link: "#", text: "Participar en el evento"}
#  - {link: "#", text: "Ser un orador"}

rightNavigationButtons:
 - {link: "#", text: "Participar evento"}
 - {link: "#", text: "Ser orador"}
 - {link: "#", text: "Registrar proyecto"}

# Hero Block
heroImage: "fundo_escuro.png"
logoUnigranrio: "logo_ar.png"
heroTitle: "Argentina Dev Day - <typeout>"
eventDate: "01 de -- de 2017"
typeoutTextValues: '"", "Build Better Together", "GDG Mendoza", "Python ", "Ruby ", "Pyladies ", "Woman Teckmakers "'
typeoutFallback: "Season"
heroButtons:
 #- {link: "https://goo.gl/forms/yD2sEXxqfsssUZLn2", text: "Seja um Palestrante"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Acerca de Argentina DevDay"
aboutBlock:
 - {title: "Talks", image: "bigdata.jpg", text: "Charlas sobre lenguajes de programación, frameworks y más." }
 - {title: "Lightning Talks", image: "iot.png", text: "Lightning Talks, charlas más rápidos en el desarrollo." }
 - {title: "Workshops", image: "dev.png", text: "Workshops en nuevos lenguajes, frameworks modernos y más." }
 - {title: "Open Source", image: "opsource.jpg", text: "Un proyecto Open Source ganará la asistencia." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "participantes", detail: ""}
 - {count: "7", specialCharacter: "+", info: "horas", detail: "charlas y contenido"}
 - {count: "10", specialCharacter: "+", info: "charlantes", detail: "grandes"}
 - {count: "1", specialCharacter: "", info: "día", detail: "puro aprendizaje"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Charlantes"
rockstarSpeakersButtonText: "Ver todos los charlantes"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Universidad Mendoza"
eventLocationLink: "#"
eventStreetAddress: "Mendoza"
eventAddressLocality: "Mendoza"
eventAddressLocalityRegion: "Mendoza"
eventPostalCode: "5500"
eventAddressCountry: "Argentina"
eventStartTime: "2017-11-19T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-11-19T17:00"
eventPlaceCoordinates: "32.8914378, -68.8621156"
mapCenterCoordinates: "32.8914378, -68.8621156"
mapMobileCenterCoordinates: "32.8914378, -68.8621156"

# Venue Block
venueBlockTitle: "Universidad Mendoza"
venueBigImage: "auditorio.jpg"
venueSmallImage1: "novaamerica.png"
venueSmallImage2: "novaamerica-2.jpg"

#venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditório"
venueFeatures: ["Buen ambiente para las conversaciones "," Una buena acústica, aire acondicionado", "Situado dentro de la Universidad "]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "e aí?"
twitterHashTag: "riodevday"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Parceiros"

partnersC4sponsorsButton: "Sea un patrocinador, por favor, póngase en contacto con nosotros por correo electrónico argentinadevday@gmail.com"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Mantenerse al día con las noticias!"
subscribeAction: "#"
# subscribeInfo: "Su dirección de correo electrónico se guardará en una lista para enviar información sobre el evento"


# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/", icon: "twitter"}
 - {link: "https://www.facebook.com/", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "#", text: "Universidad Mendoza"}
   - {link: "https://developers.google.com", text: "Google Developers"}

 -
  title: "Contactos"
  links:

   - {link: "mailto:argentinadevday@gmail.com", text: "argentinadevday@gmail.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre Nosotros"
aboutUs: "Somos un grupo de desarrolladores en varios lenguajes de programación, varias comunidades decidieron unirse a nosotros y hacer un evento que mezcla todo lo que es mejor."

# # Communities Block
# communitiesBlockTitle: "Proyectos Open Source "
# aboutUs: "Sé uno de los proyectos que ayudarán.Todos los beneficios recaudados de patrocinio del evento se destinarán a un proyecto de código abierto que será elegido por votación."


# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-22.8782071,-43.272322"
logisticsMapMobileCenterCoordinates: "-22.8782071,-43.272322"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
